name: Build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Checkout submodules
      run: git submodule update --init --recursive
    
    - name: Set up NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
    
    - name: Install liboqs dependencies
      run: sudo apt-get update && sudo apt-get install -y astyle cmake gcc ninja-build libssl-dev python3-pytest python3-pytest-xdist unzip xsltproc doxygen graphviz python3-yaml valgrind

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Gradle :core:assemble
      run: ./gradlew :core:assemble -x validateSigningProductionRelease
